language: python
python:
 - 2.6
 - 2.7
 - 3.3

env:
 - DJANGO_VERSION=1.2.7
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.10
 - DJANGO_VERSION=1.5.5
 - DJANGO_VERSION=1.6

install:
  - pip install -q mock==0.8 Django==$DJANGO_VERSION coverage coveralls
  - pip install . --use-mirrors

script:
  - coverage run --source=guardian setup.py test

after_success:
  - coverage report --omit "guardian/compat.py,guardian/testsettings.py" -m guardian/*.py
  - coveralls




matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.2.7
        - python: 3.3
          env: DJANGO_VERSION=1.3.7
        - python: 3.3
          env: DJANGO_VERSION=1.4.10

