language: python
python:
 - 2.6
 

env:
 - DJANGO_VERSION=1.2.7
 
install:
  - pip install -q mock==0.8 Django==$DJANGO_VERSION 
  - pip install . --use-mirrors

script:
  - coverage run --source=guardian setup.py test

after_success:
  - coverage report --omit "guardian/compat.py,guardian/testsettings.py" -m guardian/*.py
  - coveralls


matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.2.7
        - python: 3.3
          env: DJANGO_VERSION=1.3.7
        - python: 3.3
          env: DJANGO_VERSION=1.4.10

